### ISSUE TITLE
Can you guide to install this extension more detail ? Thanks

### ISSUE THREAD

**Issue by trionline29** [JensPLarsen/ChromeExtension-GoogleDocsUtil#1]

**Comment by JensPLarsen** [comment]
What is your issue? 

By default all you need to do is: 
1. Add the googleDocsUtil.js to your Google Extension folder
2. Add the googleDocsUtil.js as a content script in your manifest.json

**Comment by JensPLarsen** [comment]
If it is part 2, I add the googleDocsUtil.js as a content script in my manifest.json like this: 

`    "content_scripts": [{
        "all_frames": true,
        "js": [
             ...
            "googleDocsUtil.js",
            ....
        ],
        "matches": ["\u003Call_urls>"],
        "run_at": "document_end"
    }],`

**Comment by JensPLarsen** [comment]
Due to no new responses, I will close this issue and watch it as solved.
