### ISSUE TITLE
setTextCurrentCursor Issue

### ISSUE THREAD

**Issue by sandokan815** [JensPLarsen/ChromeExtension-GoogleDocsUtil#10]
After I inserted text by setTextCurrentCursor function, I can't input normal letter anymore
And also, when I press space button, it is removed
In my opinion, setTextCurrentCursor function doesn't move caret based on length of text inserted
How can I solve it?

**Comment by MrJavaWolf** [comment]
This utility does not have a "setTextCurrentCursor" function?
