### ISSUE TITLE
Google docs highlights full of Unicode zero width non-joiner

### ISSUE THREAD

**Issue by menicosia** [JensPLarsen/ChromeExtension-GoogleDocsUtil#12]
Hello! I love this helper library, we use it to capture highlights out of Google Docs.

Recently, I noticed that the text captured is now littered with `&#8204;` which appears to be unicode for [zero width non-joiner](https://www.fileformat.info/info/unicode/char/200c/index.htm). This looks fine when rendered in a web browser, but the characters really interfere when stored in a DB/reporting tool.

I'll try to see if I can PR a fix (unlikely) so proactively filing an issue in case you can help.

**Comment by JensPLarsen** [comment]
Hello! 
Google Docs is sadly a moving target, and I am not informed in any way when they make updates/changes to it (I am not part of Google in any way). 

But it appears other people have fixed it for you, please see (All hail) PR #13 

You are always welcome to make PR if you experience any more issues :)

**Comment by menicosia** [comment]
After working-around issue #14, I see clear text without zero-width non-joiners. Thank you!

Thank you @TwoLegzMosquito!

Closing.
