### ISSUE TITLE
`googleDocument.selectedText` is empty

### ISSUE THREAD

**Issue by vitaly-zdanevich** [JensPLarsen/ChromeExtension-GoogleDocsUtil#2]

**Comment by JensPLarsen** [comment]
Could you describe the problem, in which cases is it empty? Always? 
When calling the googleDocsUtil.getGoogleDocument() it returns a snapshot of how the google document looks at that exact time. 

You can always call the googleDocsUtil.getGoogleDocument() again to get a new snapshot.

**Comment by vitaly-zdanevich** [comment]
Oh, now it works. But not always correct! See

<img width="874" alt="screen shot 2017-11-22 at 9 30 35 am" src="https://user-images.githubusercontent.com/3514015/33113169-0418d8e4-cf68-11e7-9158-4f50baaf4813.png">

**Comment by vitaly-zdanevich** [comment]
Sorry I found that it was selected the second word from another user. Looks like works today...
