### ISSUE TITLE
Implement a way to write to google doc

### ISSUE THREAD

**Issue by dkbast** [JensPLarsen/ChromeExtension-GoogleDocsUtil#3]
Hi - it would be awesome to have a way to write the text back to the google-doc. Do you have any plans on implementing that?

**Comment by JensPLarsen** [comment]
Not in the near future sadly. 

A some point in the future maybe, I have been looking into it before. The idea is to send keyboard presses to the correct "div" element, or maybe use clipboard so you can send multiple characters at a time. The biggest problem currently is there is no way to tell Google Docs where in the document to add the new characters, so they will always be added where the cursor is.

**Comment by samarthagarwal** [comment]
Hi. I have tried sending clipboard events but seems like they are not propagated to the DOM. Google docs intercepts these events in some way. I also tried document.execCommand but that also doesn't work. Do you have any other ideas to select and change some text?

**Comment by MrJavaWolf** [comment]
I do not know, sorry.

Google Docs is changing the way to interact with the document: https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html 

This project no longer works with these changes.

**Comment by JensPLarsen** [comment]
I do not know, sorry.

Google Docs is changing the way to interact with the document: https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html 

This project no longer works with these changes.
