### ISSUE TITLE
`googleDocument.selectedText` is empty

### ISSUE THREAD

**Issue by menicosia** [JensPLarsen/ChromeExtension-GoogleDocsUtil#5]
Hi, I know this is a dup of #2, but I don't think I can re-open someone else's issue.

I was super-happy when I found this repo, because I want to pre-populate an extension's popup with the highlighted text, but didn't want to figure out how to tear that out of a googleDoc.

I too, am having problems with empty selectedText. I haven't started to look into if this is actually an issue with finding the caret yet.

I have a repo that demonstrates the problem: [gdocs select example](https://github.com/menicosia/gdocs-select-example)

Am I doing something wrong? Thanks.

**Comment by menicosia** [comment]
Hmm, I had used `document_end` as you mentioned [here](https://github.com/JensPLarsen/ChromeExtension-GoogleDocsUtil/issues/1#issuecomment-342207346), but it seems to work much better when using `document_idle`.

May be worth documenting?

**Comment by JensPLarsen** [comment]
Hello, document_idle looks interesting, the ChromeExtension-GoogleDocsUtil requires the page to be loaded for it to work. So if there is a better trigger than document_end it would definitely be worth looking at. I will come back to you when I have had a change to test it.
